
// gotoxy(startCol, startRow + i); i++;
// printf("            _.._     \n");
// gotoxy(startCol, startRow + i); i++;
// printf("     (`._.\"      \"._.')\n");
// gotoxy(startCol, startRow + i); i++;
// printf("      '._          _.'              /\\\n");
// gotoxy(startCol, startRow + i); i++;
// printf("       | /`-.  .-'\\ |             .'.'\n");
// gotoxy(startCol, startRow + i); i++;
// printf("       |(_()_\\/_()_)| __         ( (\n");
// gotoxy(startCol, startRow + i); i++;
// printf("       ;   ,____,   ;'  `\\        ) )\n");
// gotoxy(startCol, startRow + i); i++;
// printf("        \\  /VvvV\\  /    \\  \\.__   / /\n");
// gotoxy(startCol, startRow + i); i++;
// printf("      _/`'._----_.'      \\  \\  `\\/ /\n");
// gotoxy(startCol, startRow + i); i++;
// printf("     /  ._-_`--'     .----.  \\    /\n");
// gotoxy(startCol, startRow + i); i++;
// printf("    / _/      )     /  .------\\`.|  \n");
// gotoxy(startCol, startRow + i); i++;
// printf("   / / |    ``    _,|  (_`-'_\\   \\\n");
// gotoxy(startCol, startRow + i); i++;
// printf("  / /   \\   \\`\"\"`    \\\\\\\\     \\   \\\n");
// gotoxy(startCol, startRow + i); i++;
// printf(" / / _   \\  /                 /`  /`\n");
// gotoxy(startCol, startRow + i); i++;
// printf("/ _\\/(    | |               ./  .'_\n");
// gotoxy(startCol, startRow + i); i++;
// printf("| ( \\  '--'  \\             .'  (__)'\\\n");
// gotoxy(startCol, startRow + i); i++;
// printf("\\\\\\\\ `-------'            /________.''\n");